import Head from 'next/head';
import Navbar from './components/Navbar'
import Getstarted from './components/Getstarted'
import Planet from './components/Planet'
import Ultimate from './components/Ultimate'
import Trelloboard from './components/Trelloboard'
import Envision from './components/Envision'
import Plan from './components/Plan'
import Faq from './components/Faq'
import Mapping from './components/Mapping'
import Footer from './components/Footer'



export default function Home() {
  return (
    <div className='sm:flex sm:flex-col sm:justify-start  '>
      <Head>
        <title>mindmap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col '>
        <div className='mb-[80px]'>   <Navbar /> </div>
          <Getstarted /> 
          <Planet /> 
         <Ultimate/> 
         <Trelloboard/> 
          <Envision/>
          <Plan/>
          <Faq/>
          <Mapping/>
          <Footer/>
      </div>


    </div>
  )
}
